export const mockAgents = [
  {
    id: 1,
    name: "Customer Support Agent",
    type: "inbound",
    status: "active",
    totalCalls: 1248,
    description: "Handles customer inquiries and support tickets",
  },
  {
    id: 2,
    name: "Sales Outreach Agent",
    type: "outbound",
    status: "active",
    totalCalls: 892,
    description: "Proactive sales calls and lead qualification",
  },
  {
    id: 3,
    name: "Appointment Scheduler",
    type: "inbound",
    status: "active",
    totalCalls: 567,
    description: "Books and manages customer appointments",
  },
  {
    id: 4,
    name: "Lead Follow-up Agent",
    type: "outbound",
    status: "inactive",
    totalCalls: 324,
    description: "Follows up with potential customers",
  },
  {
    id: 5,
    name: "Technical Support Bot",
    type: "inbound",
    status: "active",
    totalCalls: 2103,
    description: "Provides technical assistance and troubleshooting",
  },
];

export const mockCallHistory = [
  {
    id: 1,
    agentName: "Customer Support Agent",
    agentType: "inbound",
    phoneNumber: "+1-555-0123",
    duration: "5:32",
    timestamp: "2025-10-02 14:23:15",
    cost: 45,
    status: "completed",
    recordingUrl:
      "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-1.mp3",
  },
  {
    id: 2,
    agentName: "Sales Outreach Agent",
    agentType: "outbound",
    phoneNumber: "+1-555-0456",
    duration: "8:15",
    timestamp: "2025-10-02 13:45:22",
    cost: 67,
    status: "completed",
    recordingUrl:
      "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-2.mp3",
  },
  {
    id: 3,
    agentName: "Technical Support Bot",
    agentType: "inbound",
    phoneNumber: "+1-555-0789",
    duration: "12:48",
    timestamp: "2025-10-02 13:12:05",
    cost: 104,
    status: "completed",
    recordingUrl:
      "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-3.mp3",
  },
  {
    id: 4,
    agentName: "Appointment Scheduler",
    agentType: "inbound",
    phoneNumber: "+1-555-0321",
    duration: "3:25",
    timestamp: "2025-10-02 12:55:33",
    cost: 28,
    status: "completed",
    recordingUrl:
      "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-4.mp3",
  },
  {
    id: 5,
    agentName: "Sales Outreach Agent",
    agentType: "outbound",
    phoneNumber: "+1-555-0654",
    duration: "1:15",
    timestamp: "2025-10-02 12:30:18",
    cost: 10,
    status: "no-answer",
    recordingUrl: null,
  },
  {
    id: 6,
    agentName: "Customer Support Agent",
    agentType: "inbound",
    phoneNumber: "+1-555-0987",
    duration: "7:42",
    timestamp: "2025-10-02 11:45:50",
    cost: 63,
    status: "completed",
    recordingUrl:
      "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-5.mp3",
  },
  {
    id: 7,
    agentName: "Lead Follow-up Agent",
    agentType: "outbound",
    phoneNumber: "+1-555-0147",
    duration: "4:33",
    timestamp: "2025-10-02 11:20:12",
    cost: 37,
    status: "completed",
    recordingUrl:
      "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-6.mp3",
  },
  {
    id: 8,
    agentName: "Technical Support Bot",
    agentType: "inbound",
    phoneNumber: "+1-555-0258",
    duration: "15:20",
    timestamp: "2025-10-02 10:55:45",
    cost: 125,
    status: "completed",
    recordingUrl:
      "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-7.mp3",
  },
  {
    id: 9,
    agentName: "Sales Outreach Agent",
    agentType: "outbound",
    phoneNumber: "+1-555-0369",
    duration: "6:18",
    timestamp: "2025-10-02 10:15:33",
    cost: 51,
    status: "completed",
    recordingUrl:
      "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-8.mp3",
  },
  {
    id: 10,
    agentName: "Appointment Scheduler",
    agentType: "inbound",
    phoneNumber: "+1-555-0741",
    duration: "2:45",
    timestamp: "2025-10-02 09:40:27",
    cost: 22,
    status: "completed",
    recordingUrl:
      "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-9.mp3",
  },
];
