export const mockAgents = [
  {
    id: 1,
    name: "Customer Support Agent",
    type: "inbound",
    status: "active",
    totalCalls: 1248,
    description: "Handles customer inquiries and support tickets",
  },
  {
    id: 2,
    name: "Sales Outreach Agent",
    type: "outbound",
    status: "active",
    totalCalls: 892,
    description: "Proactive sales calls and lead qualification",
  },
  {
    id: 3,
    name: "Appointment Scheduler",
    type: "inbound",
    status: "active",
    totalCalls: 567,
    description: "Books and manages customer appointments",
  },
  {
    id: 4,
    name: "Lead Follow-up Agent",
    type: "outbound",
    status: "inactive",
    totalCalls: 324,
    description: "Follows up with potential customers",
  },
  {
    id: 5,
    name: "Technical Support Bot",
    type: "inbound",
    status: "active",
    totalCalls: 2103,
    description: "Provides technical assistance and troubleshooting",
  },
];

export const mockCallHistory = [
  {
    id: 1,
    agentName: "Customer Support Agent",
    agentType: "inbound",
    phoneNumber: "+1-555-0123",
    duration: "5:32",
    timestamp: "2025-10-02 14:23:15",
    cost: 45,
    status: "completed",
    recordingUrl:
      "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-1.mp3",
  },
  {
    id: 2,
    agentName: "Sales Outreach Agent",
    agentType: "outbound",
    phoneNumber: "+1-555-0456",
    duration: "8:15",
    timestamp: "2025-10-02 13:45:22",
    cost: 67,
    status: "completed",
    recordingUrl:
      "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-2.mp3",
  },
  {
    id: 3,
    agentName: "Technical Support Bot",
    agentType: "inbound",
    phoneNumber: "+1-555-0789",
    duration: "12:48",
    timestamp: "2025-10-02 13:12:05",
    cost: 104,
    status: "completed",
    recordingUrl:
      "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-3.mp3",
  },
  {
    id: 4,
    agentName: "Appointment Scheduler",
    agentType: "inbound",
    phoneNumber: "+1-555-0321",
    duration: "3:25",
    timestamp: "2025-10-02 12:55:33",
    cost: 28,
    status: "completed",
    recordingUrl:
      "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-4.mp3",
  },
  {
    id: 5,
    agentName: "Sales Outreach Agent",
    agentType: "outbound",
    phoneNumber: "+1-555-0654",
    duration: "1:15",
    timestamp: "2025-10-02 12:30:18",
    cost: 10,
    status: "no-answer",
    recordingUrl: null,
  },
  {
    id: 6,
    agentName: "Customer Support Agent",
    agentType: "inbound",
    phoneNumber: "+1-555-0987",
    duration: "7:42",
    timestamp: "2025-10-02 11:45:50",
    cost: 63,
    status: "completed",
    recordingUrl:
      "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-5.mp3",
  },
  {
    id: 7,
    agentName: "Lead Follow-up Agent",
    agentType: "outbound",
    phoneNumber: "+1-555-0147",
    duration: "4:33",
    timestamp: "2025-10-02 11:20:12",
    cost: 37,
    status: "completed",
    recordingUrl:
      "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-6.mp3",
  },
  {
    id: 8,
    agentName: "Technical Support Bot",
    agentType: "inbound",
    phoneNumber: "+1-555-0258",
    duration: "15:20",
    timestamp: "2025-10-02 10:55:45",
    cost: 125,
    status: "completed",
    recordingUrl:
      "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-7.mp3",
  },
  {
    id: 9,
    agentName: "Sales Outreach Agent",
    agentType: "outbound",
    phoneNumber: "+1-555-0369",
    duration: "6:18",
    timestamp: "2025-10-02 10:15:33",
    cost: 51,
    status: "completed",
    recordingUrl:
      "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-8.mp3",
  },
  {
    id: 10,
    agentName: "Appointment Scheduler",
    agentType: "inbound",
    phoneNumber: "+1-555-0741",
    duration: "2:45",
    timestamp: "2025-10-02 09:40:27",
    cost: 22,
    status: "completed",
    recordingUrl:
      "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-9.mp3",
  },
];

export const mockLeads = [
  {
    id: "lead_001",
    name: "Maria Santos",
    email: "maria.santos@example.com",
    phone: "+1-555-201-8899",
    company: "Bright Smiles Dental",
    address: "123 Market St, San Francisco, CA",
    agentId: "agent_001",
    reason: "New patient cleaning",
    visitTime: "2025-10-05T10:30:00.000Z",
    agentName: "Customer Support Agent",
    createdAt: "2025-10-02 15:10:12",
    status: "new",
  },
  {
    id: "lead_002",
    name: "Kevin Patel",
    email: "kevin.patel@example.com",
    phone: "+1-555-112-4433",
    company: "Patel Family Dentistry",
    address: "980 Lakeshore Dr, Chicago, IL",
    agentId: "agent_002",
    reason: "Emergency tooth pain",
    visitTime: "2025-10-03T14:00:00.000Z",
    agentName: "Appointment Scheduler",
    createdAt: "2025-10-02 14:41:03",
    status: "contacted",
  },
  {
    id: "lead_003",
    name: "Ava Brooks",
    email: "ava.brooks@example.com",
    phone: "+1-555-330-1098",
    company: "Brooks Orthodontics",
    address: "56 Glenwood Ave, Austin, TX",
    agentId: "agent_003",
    reason: "Invisalign consult",
    visitTime: "2025-10-07T09:15:00.000Z",
    agentName: "Sales Outreach Agent",
    createdAt: "2025-10-02 13:58:27",
    status: "qualified",
  },
];

export const mockAppointments = [
  {
    id: "appt_001",
    patientName: "Maria Santos",
    date: "2025-10-05",
    time: "10:30 AM",
    timezone: "America/Los_Angeles",
    type: "Cleaning",
    agentName: "Appointment Scheduler",
    status: "confirmed",
    source: "Cal.com",
  },
  {
    id: "appt_002",
    patientName: "Kevin Patel",
    date: "2025-10-03",
    time: "2:00 PM",
    timezone: "America/Chicago",
    type: "Emergency",
    agentName: "Appointment Scheduler",
    status: "pending",
    source: "Cal.com",
  },
  {
    id: "appt_003",
    patientName: "Ava Brooks",
    date: "2025-10-07",
    time: "9:00 AM",
    timezone: "America/New_York",
    type: "Consultation",
    agentName: "Sales Outreach Agent",
    status: "confirmed",
    source: "Cal.com",
  },
];
